apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: gateway
  name: gateway
subjects:
- kind: ServiceAccount
  # Reference to upper's `metadata.name`
  name: default
  # Reference to upper's `metadata.namespace`
  namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
spec:
  replicas: 1
  selector:
    matchLabels:
      run: gateway
  template:
    metadata:
      labels:
        run: gateway
    spec:
      containers:
      - image: gcr.io/vaulted-channel-252309/gateway:latest
        name: gateway
        ports:
        - containerPort: 8080