apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: gateway
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      run: gateway
  template:
    metadata:
      labels:
        run: gateway
    spec:
      containers:
      - image: gcr.io/vaulted-channel-252309/gateway:latest
        name: gateway
        ports:
        - containerPort: 8080